### PR TITLE
Fix CI and Rails 7.1 compatibility on main

### LINKED ISSUE #106: CI is not being executed against Rails 7.1 stable (and probably 7.1 compatibility is broken on main)
Hello,

I was submitting a PR related to improve the CI by fixing SQL dependency, run against latest stable Rails and Ruby version, run experimental versions against Rails edge and Ruby head, and I've noticed that the 7.1 file is using rails-edge

Ref: https://github.com/DatabaseCleaner/database_cleaner-active_record/actions/runs/9441466205/job/26002219838#step:4:714

https://github.com/DatabaseCleaner/database_cleaner-active_record/blob/0b0bfc4175c228aa8e83990dfb24ea48dedd59f3/gemfiles/rails_7.1.gemfile#L6

So this leads to a false positive, because when testing against 7.1 stable the CI fails

Ref: https://github.com/tagliala/database_cleaner-active_record/actions/runs/9446754110

https://github.com/tagliala/database_cleaner-active_record/actions/runs/9446754110/job/26017081319#step:6:309

```
     Failure/Error: ::ActiveRecord::Base.connection_pool.schema_migration.table_name
```

### PR DESCRIPTION
**Pull request by tagliala**
Improve CI

Stable builds:
- Test against Ruby 3.3 stable
- Test against Rails 7.1 stable
- Test against Rails 7.2 beta

Experimental builds:
- Test against Rails edge (previously: 7.1, ref: #106)
- Test against Ruby head

Fixes:
- Fix sqlite3 dependency on old Rails versions

Updates:
- Update GitHub actions

Readability:
- Sort and group inclusion and exclusions in CI matrix

---

Fix Rails 7.1 compatibility

Also:
- Invert the logic to make the conditional more readable
- Add "alpha" to version to include pre-releases

ActiveRecord:
- 7.2: `Base.connection_pool.schema_migration.table_name`
- 7.1, 7.0, 6.x: `Base.connection.schema_migration.table_name`
- 5.x: `SchemaMigration.table_name`

---

Use `respond_to?` to determine the schema migration table name

Close #106

### CODE REVIEW

File: lib/database_cleaner/active_record/base.rb [hunk 1]
```diff
@@ -15,9 +15,9 @@ def self.config_file_location
 
     class Base < DatabaseCleaner::Strategy
       def self.migration_table_name
-        if Gem::Version.new("7.1.0") < ::ActiveRecord.version
+        if ::ActiveRecord::Base.connection_pool.respond_to?(:schema_migration) # Rails >= 7.2
           ::ActiveRecord::Base.connection_pool.schema_migration.table_name
-        elsif Gem::Version.new("6.0.0") <= ::ActiveRecord.version
+        elsif ::ActiveRecord::Base.connection.respond_to?(:schema_migration) # Rails >= 6.0
```
Comment (tagliala) [inline lib/database_cleaner/active_record/base.rb:20]: opinionated change in a separate commit, feel free to remove the last commit to use a version-based comparison

**Comment by mamhoff** [comment]
This fixes a bug that's currently affecting people. It would be fantastic if this were released.

**Review by etagwerker — APPROVED** [review]
@tagliala Looks good, thank you! ❤️
